service: hotline-apply

provider:
    name: aws
    runtime: nodejs8.10
    region: us-east-1
    stage: ${opt:stage, 'prod'}
    memorySize: 256
    environment:
        NODE_ENV: ${self:provider.stage, 'prod'}
        SESSION_TABLE: hotline-apply-session
        VAULT_ADDR: ${opt:vault-address}
        VAULT_ROLE_ID: ${opt:vault-role-id}
        VAULT_SECRET_ID: ${opt:vault-secret-id}

plugins:
    - serverless-plugin-typescript
    - serverless-domain-manager
    - serverless-offline

custom:
    customDomain:
        domainName: api.hotline.gg
        stage: ${self:provider.stage}
        certificateName: 'hotline.gg'
        createRoute53Record: false

functions:
    app:
        handler: src/index.handler
        events:
            -   http: ANY /
            -   http: 'ANY {proxy+}'

resources:
    Resources:
        ApiGatewayPolicy:
            Type: "AWS::IAM::Policy"
            Properties:
                Roles: [{Ref: IamRoleLambdaExecution}]
                PolicyName: api-gateway
                PolicyDocument:
                    Version: '2012-10-17'
                    Statement:
                        -   Effect: Allow
                            Action:
                                - apigateway:POST
                            Resource: !Sub arn:aws:apigateway:us-east-1::/domainnames
                        -   Effect: Allow
                            Action:
                                - apigateway:GET
                                - apigateway:DELETE
                            Resource: !Sub arn:aws:apigateway:us-east-1::/domainnames/*
                        -   Effect: Allow
                            Action:
                                - apigateway:POST
                            Resource: !Sub arn:aws:apigateway:us-east-1::/domainnames/*/basepathmappings
                        -   Effect: Allow
                            Action:
                                - cloudfront:UpdateDistribution
                            Resource: '*'
                        -   Effect: Allow
                            Action:
                                - route53:ListHostedZones
                            Resource: '*'
                        -   Effect: Allow
                            Action:
                                - acm:ListCertificates
                            Resource: '*'
